### ISSUE TITLE
Doesn't work with Premium Storage

### ISSUE THREAD

**Issue by colemickens** [theobolo/kube-registry-azure#1]
Hi Theo,

I know you observed this already but I wanted to file it here as a starting place. I suspect there's a bug in `docker-registry`, now called [`docker-distribution`](https://github.com/docker/distribution) or in the version of the Go SDK that `docker-distribution` uses.

`2016-06-30T23:18:57.951489624Z 127.0.0.1 - - [30/Jun/2016:23:18:57 +0000] "POST /v2/polykube-www/blobs/uploads/?from=polykube-www&mount=sha256%3A51f5c6a04d83efd2d45c5fd59537218924bc46705e3de6ffc8bc07b51481610b HTTP/1.1" 500 418 "" "docker/1.10.3 go/go1.6.1 git-commit/20f81dd kernel/4.4.0-28-generic os/linux arch/amd64"`

`2016-06-30T23:19:02.450195753Z time="2016-06-30T23:19:02Z" level=error msg="response completed with error" err.code=unknown err.detail="azure: storage: service returned error: StatusCode=400, ErrorCode=InvalidHeaderValue, ErrorMessage=The value for one of the HTTP headers is not in the correct format.\nRequestId:\nTime:2016-06-30T23:19:02.5897758Z, RequestId=7e11fc4a-001c-0005-7625-d3cf9f000000, QueryParameterName=, QueryParameterValue=" err.message="unknown error" go.version=go1.6.2 http.request.host="localhost:5000" http.request.id=b4098253-8839-46be-9bd4-d8846ec77eea http.request.method=POST http.request.remoteaddr="127.0.0.1:45308" http.request.uri="/v2/polykube-aspnet-api/blobs/uploads/" http.request.useragent="docker/1.10.3 go/go1.6.1 git-commit/20f81dd kernel/4.4.0-28-generic os/linux arch/amd64" http.response.contenttype="application/json; charset=utf-8" http.response.duration=83.84251ms http.response.status=500 http.response.written=418 instance.id=9cd62286-e1c3-4d56-a473-96331ac5e70e vars.name=polykube-aspnet-api version=v2.4.1` 

CC: @ahmetalpbalkan

**Comment by theobolo** [comment]
I tried with the last distribution/docker image the version=v2.5.0-rc.1 and it's the same problem.

It's seems that the Premium Storage is not exactly working as the same way than the Standard One.
The Docker Registry server is able to create the base blob object : "registry" but then can't create the blob containers /v2/"image"/blobs/update .... as it does on the Standard one.

Think that the Azure blob storage implementation on Docker registry is a fresh feature linked with the release of the Azure Container Service, maybe that's why there isn't a full support of the entire Azure Storage and specifically the Premium One, i hope it will be soon :D

By the way as you saw the Premium Storage is really important according to the real slow performances on a Standard One :/ 

I faced a similar problem about the difference about the Premium Storage Blob schem and the Standard Storage schem, but can't remember on what :P

**Comment by ahmetalpbalkan** [comment]
@colemickens the blob upload code in the registry driver has been changed after me (to use AppendBlob). There might be an issue about that.

Can you please grab the RequestId above and query it via our internal tools as the header does not reveal much info?

**Comment by ahmetalpbalkan** [comment]
@theobolo If I remember correctly, premium storage is only for Disks (page blobs) and we don't use that type of blobs in the registry for various reasons. 

Honestly we haven't super closely looked at the performance of the driver, it very well might be that we could do some parallelization to increase the throughput or various tricks like adjusting the chunk size more appropriately. I suppose the perf will get better, but it probably will never be close to disk write speed as there's a lot of back and forth traffic between registry and Azure Storage.

**Comment by colemickens** [comment]
😞 [Currently, Premium Storage does not support Azure Block Blobs, Azure Append Blobs, Azure Files, Azure Tables, or Azure Queues.](https://azure.microsoft.com/en-us/documentation/articles/storage-premium-storage/).
